In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/migue/OneDrive/Documentos/Football_Analysis/player_gca.csv')

In [13]:
df.head()

,player,position,team,age,birth_year,FullGameTime,sca,sca_per90,sca_passes_live,sca_passes_dead,...,sca_fouled,sca_defense,gca,gca_per90,gca_passes_live,gca_passes_dead,gca_dribbles,gca_shots,gca_fouled,gca_defense
0,Aaron Mooy,MF,Australia,32-094,1990,4.0,5.0,1.25,2.0,2.0,...,1.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
1,Aaron Ramsey,MF,Wales,31-357,1990,3.0,3.0,1.02,2.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
2,Abdelhamid Sabiri,MF,Morocco,26-020,1996,2.0,4.0,2.40,2.0,1.0,...,0.0,0.0,1.0,0.60,0.0,1.0,0.0,0.0,0.0,0.0
3,Abdelkarim Hassan,DF,Qatar,29-112,1993,3.0,4.0,1.33,4.0,0.0,...,0.0,0.0,1.0,0.33,1.0,0.0,0.0,0.0,0.0,0.0
4,Abderrazak Hamdallah,FW,Morocco,32-001,1990,0.8,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
df.tail()

,player,position,team,age,birth_year,FullGameTime,sca,sca_per90,sca_passes_live,sca_passes_dead,...,sca_fouled,sca_defense,gca,gca_per90,gca_passes_live,gca_passes_dead,gca_dribbles,gca_shots,gca_fouled,gca_defense
675,Ángel Di María,MF,Argentina,34-307,1988,3.2,21.0,6.77,16.0,3.0,...,1.0,0.0,4.0,1.29,2.0,0.0,1.0,0.0,1.0,0.0
676,Ángelo Preciado,DF,Ecuador,24-303,1998,2.9,5.0,1.70,4.0,0.0,...,0.0,0.0,1.0,0.34,1.0,0.0,0.0,0.0,0.0,0.0
677,Éder Militão,DF,Brazil,24-334,1998,3.9,6.0,1.56,5.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
678,Óscar Duarte,DF,Costa Rica,33-198,1989,3.0,1.0,0.33,1.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
679,İlkay Gündoğan,MF,Germany,32-055,1990,2.1,6.0,2.86,6.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df.shape

(680, 22)

In [6]:
df.columns

Index(['player', 'position', 'team', 'age', 'birth_year', 'minutes_90s', 'sca',
       'sca_per90', 'sca_passes_live', 'sca_passes_dead', 'sca_dribbles',
       'sca_shots', 'sca_fouled', 'sca_defense', 'gca', 'gca_per90',
       'gca_passes_live', 'gca_passes_dead', 'gca_dribbles', 'gca_shots',
       'gca_fouled', 'gca_defense'],
      dtype='object')

In [7]:
df.describe()

,birth_year,minutes_90s,sca,sca_per90,sca_passes_live,sca_passes_dead,sca_dribbles,sca_shots,sca_fouled,sca_defense,gca,gca_per90,gca_passes_live,gca_passes_dead,gca_dribbles,gca_shots,gca_fouled,gca_defense
count,680.000000,680.000000,677.000000,675.000000,677.000000,677.000000,677.000000,677.000000,677.000000,677.000000,677.000000,675.000000,677.000000,677.000000,677.000000,677.000000,677.000000,677.000000
mean,1994.913235,2.124265,3.760709,2.088978,2.787297,0.322009,0.165436,0.243722,0.187592,0.054653,0.429838,0.244148,0.320532,0.017725,0.022157,0.029542,0.038405,0.001477
std,4.156348,1.642302,4.891007,3.091478,3.534147,0.975894,0.572381,0.635240,0.520548,0.257944,0.942046,1.181861,0.741265,0.132049,0.157023,0.222310,0.192313,0.038433
min,1983.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1992.000000,0.800000,1.000000,0.330000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1995.000000,1.900000,2.000000,1.460000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1998.000000,3.000000,5.000000,2.810000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.190000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2004.000000,7.700000,46.000000,45.000000,28.000000,12.000000,7.000000,8.000000,5.000000,3.000000,11.000000,22.500000,7.000000,1.000000,2.000000,4.000000,1.000000,1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 680 entries, 0 to 679
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   player           680 non-null    object
 1   position         680 non-null    object
 2   team             680 non-null    object
 3   age              680 non-null    object
 4   birth_year       680 non-null    int64
 5   minutes_90s      680 non-null    float64
 6   sca              677 non-null    float64
 7   sca_per90        675 non-null    float64
 8   sca_passes_live  677 non-null    float64
 9   sca_passes_dead  677 non-null    float64
 10  sca_dribbles     677 non-null    float64
 11  sca_shots        677 non-null    float64
 12  sca_fouled       677 non-null    float64
 13  sca_defense      677 non-null    float64
 14  gca              677 non-null    float64
 15  gca_per90        675 non-null    float64
 16  gca_passes_live  677 non-null    float64
 17  gca_passes_dead  677 non-null    float64
 18  gca_dribbles     677 non-null    float64
 19  gca_shots        677 non-null    float64
 20  gca_fouled       677 non-null    float64
 21  gca_defense      677 non-null    float64
dtypes: float64(17), int64(1), object(4)
memory usage: 117.0+ KB

In [9]:
df.isnull().sum()

player             0
position           0
team               0
age                0
birth_year         0
minutes_90s        0
sca                3
sca_per90          5
sca_passes_live    3
sca_passes_dead    3
sca_dribbles       3
sca_shots          3
sca_fouled         3
sca_defense        3
gca                3
gca_per90          5
gca_passes_live    3
gca_passes_dead    3
gca_dribbles       3
gca_shots          3
gca_fouled         3
gca_defense        3
dtype: int64

In [10]:
df = df.rename(columns={'minutes_90s':'FullGameTime'})

In [12]:
df = df.rename(columns=lambda x: x.split(' ')[-1] if '_' in x else x)

In [14]:
df.loc[0:7, 'player':'age']

                  player position       team     age
0             Aaron Mooy       MF  Australia  32-094
1           Aaron Ramsey       MF      Wales  31-357
2      Abdelhamid Sabiri       MF    Morocco  26-020
3      Abdelkarim Hassan       DF      Qatar  29-112
4   Abderrazak Hamdallah       FW    Morocco  32-001
5  Abdessamad Ezzalzouli       FW    Morocco  21-001
6           Abdou Diallo       DF    Senegal  26-228
7  Abdul Fatawu Issahaku       FW      Ghana  18-285

In [16]:
df.iloc[0:5,0:5]

                 player position       team     age  birth_year
0            Aaron Mooy       MF  Australia  32-094        1990
1          Aaron Ramsey       MF      Wales  31-357        1990
2     Abdelhamid Sabiri       MF    Morocco  26-020        1996
3     Abdelkarim Hassan       DF      Qatar  29-112        1993
4  Abderrazak Hamdallah       FW    Morocco  32-001        1990

In [17]:
wc = df[df['team']=='Brazil']
wc.head()

,player,position,team,age,birth_year,FullGameTime,sca,sca_per90,sca_passes_live,sca_passes_dead,...,sca_fouled,sca_defense,gca,gca_per90,gca_passes_live,gca_passes_dead,gca_dribbles,gca_shots,gca_fouled,gca_defense
26,Alex Sandro,DF,Brazil,31-326,1991,2.1,6.0,3.09,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,Alex Telles,DF,Brazil,30-003,1992,0.7,1.0,1.55,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,Alisson,GK,Brazil,30-077,1992,4.2,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67,Antony,FW,Brazil,22-297,2000,1.9,7.0,4.44,5.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
104,Bruno Guimarães,MF,Brazil,25-032,1997,0.8,1.0,1.30,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
wc = df[(df['team'] == 'Argentina') & (df['FullGameTime']>1.0)]
print(wc.head())

                  player position       team     age  birth_year  \
30   Alexis Mac Allister       MF  Argentina  23-359        1998
133      Cristian Romero       DF  Argentina  24-235        1998
184    Emiliano Martínez       GK  Argentina  30-107        1992
187       Enzo Fernández       MF  Argentina  21-335        2001
227      Gonzalo Montiel       DF  Argentina  25-351        1997

     FullGameTime   sca  sca_per90  sca_passes_live  sca_passes_dead  ...  \
30            6.1  16.0       2.77             16.0              0.0  ...
133           6.1   3.0       0.52              2.0              1.0  ...
184           7.7   0.0       0.00              0.0              0.0  ...
187           6.3  17.0       3.04             15.0              0.0  ...
227           1.3   3.0       3.70              2.0              1.0  ...

     sca_fouled  sca_defense  gca  gca_per90  gca_passes_live  \
30          0.0          0.0  2.0       0.35              2.0
133         0.0          0.0  1.0       0.17              0.0
184         0.0          0.0  0.0       0.00              0.0
187         0.0          0.0  4.0       0.71              3.0
227         0.0          0.0  0.0       0.00              0.0

     gca_passes_dead  gca_dribbles  gca_shots  gca_fouled  gca_defense
30               0.0           0.0        0.0         0.0          0.0
133              1.0           0.0        0.0         0.0          0.0
184              0.0           0.0        0.0         0.0          0.0
187              0.0           1.0        0.0         0.0          0.0
227              0.0           0.0        0.0         0.0          0.0

[5 rows x 22 columns]

In [23]:
df.sort_values(by='team', ascending=False)

,player,position,team,age,birth_year,FullGameTime,sca,sca_per90,sca_passes_live,sca_passes_dead,...,sca_fouled,sca_defense,gca,gca_per90,gca_passes_live,gca_passes_dead,gca_dribbles,gca_shots,gca_fouled,gca_defense
122,Chris Mepham,DF,Wales,25-043,1997,3.0,3.0,1.00,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
299,Joe Morrell,MF,Wales,25-349,1997,0.4,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aaron Ramsey,MF,Wales,31-357,1990,3.0,3.0,1.02,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
91,Ben Davies,DF,Wales,29-238,1993,2.6,4.0,1.51,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
478,Neco Williams,DF,Wales,21-249,2001,2.3,3.0,1.33,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,Papu Gómez,MF,Argentina,34-306,1988,1.2,1.0,0.84,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
516,Paulo Dybala,FW,Argentina,29-033,1993,0.2,1.0,5.29,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
220,Germán Pezzella,DF,Argentina,31-174,1991,0.7,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
227,Gonzalo Montiel,DF,Argentina,25-351,1997,1.3,3.0,3.70,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
492,Nicolás Tagliafico,DF,Argentina,30-109,1992,4.1,4.0,1.05,3.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
wc[['player','sca_defense']].sort_values('sca_defense').head(20)

                  player  sca_defense
30   Alexis Mac Allister          0.0
133      Cristian Romero          0.0
184    Emiliano Martínez          0.0
187       Enzo Fernández          0.0
227      Gonzalo Montiel          0.0
330       Julián Álvarez          0.0
378     Lautaro Martínez          0.0
381      Leandro Paredes          0.0
407         Marcos Acuña          0.0
513           Papu Gómez          0.0
675       Ángel Di María          0.0
389    Lisandro Martínez          1.0
470        Nahuel Molina          1.0
491     Nicolás Otamendi          1.0
492   Nicolás Tagliafico          1.0
388         Lionel Messi          1.0
551      Rodrigo De Paul          1.0

In [ ]:
n